### ISSUE TITLE
Implement mlflow_log_artifact()

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/mlflow-original#12]
`mlflow_log_artifact()` is currently not implement, it's not available in the REST API.

- [x] Support to log local artifacts
- [x] Support to log to Amazon S3
- [x] Support to log to Google Store
- [x] Support to log to Azure Store

**Comment by kevinykuo** [comment]
Did a quick parity check and looks like we'll need `mlflow_log_artifact()`, `mlflow_log_artifacts()`, and `mlflow_download_artifacts()` for each `ArtifactRepository` (s3, azure, etc.). I *think* we might get `mlflow_list_artifacts()` "for free" from the REST API, but haven't tested.

**Comment by javierluraschi** [comment]
Implemented with https://github.com/rstudio/mlflow/commit/c46cdf6699e9d097d0728ded579d08f66e2c3c7c, https://github.com/rstudio/mlflow/commit/6faef763e68df2a71d2aa5b06656a5faaa7bf076 and https://github.com/rstudio/mlflow/commit/e2736031f0bbfbf91996952c111901bf03d6a7a7
