### ISSUE TITLE
Fix REST wrappers and docs

### ISSUE THREAD

**Issue by kevinykuo** [rstudio/mlflow-original#23]
Changes to reflect https://github.com/mlflow/mlflow/pull/284 and https://github.com/mlflow/mlflow/pull/232.

**Comment by harryprince** [comment]
README installation is wrong, here is right way:
`devtools::install_github("rstudio/mlflow",subdir="R/mlflow")`

**Comment by kevinykuo** [comment]
Thanks @harryprince! Fixed in https://github.com/rstudio/mlflow/commit/c93787637764b5ce8050fa8383c2c07dfa2b4e85. FYI @javierluraschi the Rmd wouldn't knit so I set the `mlflow_predict()` block to `eval = FALSE` for now.

**Comment by javierluraschi** [comment]
Fixed the readme to make `mlflow_rfunc_predict()` executable again, let me know if you can't knit it since that might mean there is a bug in `mlflow`!
