### ISSUE TITLE
Implement `mlflow_run()`

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/mlflow-original#5]
- [x] Support for parameters with `tfruns` code.
- [x] Support for running the code

```
mlflow_run("train.R", 10, 11)
```

**Comment by kevinykuo** [comment]
Taking a stab at this.

**Comment by jjallaire** [comment]
You are going to need other parameters to `mflow_run` so I think you will need to do `params = list()` for the parameters rather than just using `...`

**Comment by kevinykuo** [comment]
Initial implementation merged with https://github.com/rstudio/mlflow/pull/10. Still need to add additional parameters, handling directory paths, and reading `MLProject` files.

`mlflow run` currently handles grabbing projects from GitHub so we may want to dispatch to the CLI when we detect a GitHub URI. Running projects without `MLProject` will be implemented with this upstream PR: https://github.com/mlflow/mlflow/pull/218.

**Comment by kevinykuo** [comment]
Closed via https://github.com/rstudio/mlflow/pull/16
