### ISSUE TITLE
Implement model dependencies

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/mlflow-original#8]
- [x] Get dependencies with `packrat` when triggering `mlflow_run()` and `mlflow_save_model()`.
- [x] Option to restore packages when running `mlflow_run()`, `mlflow_serve()`, `mlflow_predict()`.
- [x] Add function to explicitly create dependencies and explicitly restore dependencies.

**Comment by kevinykuo** [comment]
Note that the dependencies needed for `mlflow_run()` and `mlflow_save_model()` may be different, and one may not necessarily be a subset of the other.

**Comment by jjallaire** [comment]
The way packrat currently analyzes dependencies is just based on the source code contained within a directory, so in practice we may end up having the same list of dependencies here.

**Comment by jjallaire** [comment]
I'm not sure whether we want to restore dependencies automatically for `mlflow_run()`, `mlflow_serve()`, etc. as this will in practice take several minutes (even up to 30 minutes if stringi is involved). There is also the question of where to restore the dependencies to -- if it's ephemeral (e.g. a temp dir) then you are looking at paying the ~ 15 minutes for every invocation. If it's permanent then you are looking at creating a packrat directory within the project directory which will have implications for ordinary training work (i.e. we don't want to force packrat on people just b/c they are using mlflow).

You could take the same approach as CloudML where it's ephemeral *but* we use a packrat cache. In this scenario you might get reasonable performance when the cache hit rate is extremely high.

I think packrat is messy enough that we probably want to make this somewhat explicit but this definitely bears further discussion (as going with to restoring by default certainly creates it's own potential failure modes).

**Comment by javierluraschi** [comment]
See https://github.com/rstudio/mlflow/compare/054ed8f7e459c9ee42f2e9a29fa0db6cef018003...8855714a8a5b8971e50a410dc704f82a56a9ccb9
